# Generated by Django 2.2.6 on 2019-10-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191021_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryitem',
            name='keyword',
            field=models.CharField(max_length=40),
        ),
    ]
